name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      working-directory: ./prompetize
      run: npm ci
      
    - name: Run tests
      working-directory: ./prompetize
      run: npm test
      
    - name: Build extension
      working-directory: ./prompetize
      run: |
        npm run build
        
    - name: Upload extension artifact
      uses: actions/upload-artifact@v2
      with:
        name: chrome-extension
        path: prompetize/dist
